"""fix tutors connection

Revision ID: 6867f7a322de
Revises: c6a18355ca2e
Create Date: 2025-10-04 20:24:23.531457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6867f7a322de'
down_revision: Union[str, Sequence[str], None] = 'c6a18355ca2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tutor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tutor_module',
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.tutor_id'], ),
    sa.PrimaryKeyConstraint('tutor_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_module')
    op.drop_table('tutors')
    # ### end Alembic commands ###
